### ISSUE TITLE
-p flag not working

### ISSUE THREAD

**Issue by Arshitha** [nimh-dsst/dsst-defacing-pipeline#38]
Running the pipeline on a single participant with -p is not working. The program just prints dataset summary and quits without an error.

**Comment by yarikoptic** [comment]
for me it is errorring our differently:

```
yoh@typhon:/mnt/DATA/data/yoh/1076_spacetop$ ../dsst-defacing-pipeline/dsst-defacing-pipeline-test.sing -p 0001 -- . derivatives/dss-defacing-1
Traceback (most recent call last):
  File "/opt/dsst-defacing-pipeline/run.py", line 192, in <module>
    main()
  File "/opt/dsst-defacing-pipeline/run.py", line 106, in main
    mapping_dict = generate_mappings.crawl(input_dir, output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dsst-defacing-pipeline/generate_mappings.py", line 196, in crawl
    f3.write('\n'.join([str(p) for p in no_anat_dirs]))
                                        ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'no_anat_dirs' where it is not associated with a value
```
(using container from #41) .

**Comment by yarikoptic** [comment]
reason for my error -- wrong code assumption that we do have some `sub-` folder  -- in my case I might have forgot to mount/be in a different folder etc.

I will propose a quick PR...
